### ISSUE TITLE
Write a purpose statement for the project

### ISSUE THREAD

**Issue by Henry-Gao-2004** [Tomato-Tigers/TeamForge#5]

**Comment by Henry-Gao-2004** [comment]
Example: 
The purpose of this software is to ...

**Comment by alexandraiotzova** [comment]
The purpose of this software is to create a tailored social platform for CS 370 students to enhance team-building, resulting in stronger project outcomes. By leveraging a standard graph, composing of nodes and edges, the platform will serve as the hub for team member information. Nodes represent student profiles with personal and project-related information, including tags representing interests, while Edges indicate the key relationship of mutual interest between students. Restricting its use to this class will inform its design and allow for benefit from class feedback; our experiences will also guide its development.
