### ISSUE TITLE
Node.js / React access database in AWS Neptune

### ISSUE THREAD

**Issue by Henry-Gao-2004** [Tomato-Tigers/TeamForge#60]

**Comment by Henry-Gao-2004** [comment]
@nicholasueki @katyakurchin @xavii-p Please choose an area and focus on that! 
Here are a few options: 

- Germlin
- OpenCypher
- EC2
- SPARQL
- You can also choose something else, but not something that has been chosen!

**Comment by Henry-Gao-2004** [comment]
I will research the EC2 area.

**Comment by katyakurchin** [comment]
I can research SPARQL since Nick was already looking at Gremlin before

**Comment by nicholasueki** [comment]
I found some more details on the differences between OpenCypher and Gremlin. Essentially, Gremlin was designed to appeal to programmers while OpenCypher was made to feel like SQL. 

https://docs.google.com/document/d/1XZtRCCTdWLuKguBhiexq6aY9gqQnptZX2SnPBwiOuTI/edit?usp=sharing

**Comment by katyakurchin** [comment]
I found a tutorial for SPARQL : https://jena.apache.org/tutorials/sparql.html 
I will go more in depth over the weekend. SPARQL is essentially a query language for RDFs

**Comment by Henry-Gao-2004** [comment]
Hi guys! I got it working! 
![image](https://github.com/Tomato-Tigers/TeamForge/assets/77124321/00aa1129-aef3-4a44-9af2-6213beddd65c)
Now I can connect to Neptune using EC2, and use SSH to connect to EC2!
